on: [push, pull_request]

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        browser: [Chrome, Firefox, Safari, IE]
        exclude:
          - os: macos-latest
            browser: IE
          - os: windows-latest
            browser: Safari
          - os: ubuntu-latest
            browser: Safari
          - os: ubuntu-latest
            browser: IE

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: enable-safaridriver
        if: ${{ matrix.os == 'macos-latest' }}
        run: sudo safaridriver --enable

      - name: install-deps
        run: |
          python -m pip install -r ./requirements.txt
          python -m pip install coveralls pytest mock

      - name: start-test-server-nix
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          cd tests/demo-app
          python ./runserver.py > /dev/null 2>&1 &
          cd ../..

      - name: regedit
        if: ${{ matrix.os == 'windows-latest' }}
        shell: cmd
        run: |
          regedit /s .\ci\bfcache.reg

      - name: start-test-server-windows
        if: ${{ matrix.os == 'windows-latest' }}
        shell: powershell
        run: |
          Import-Module WebAdministration
          New-WebSite -Name demoapp -Port 8000 -PhysicalPath "${env:GITHUB_WORKSPACE}\tests\demo-app"

      - name: run-tests
        env:
          BEHAVE_WEBDRIVER: ${{ matrix.browser }}
          BEHAVE_WEBDRIVER_HEADLESS: "1"
        run: |
         coverage run -m behave tests/features
         coverage run -a -m pytest tests/unittests

      - name: coveralls
        if: ${{ success() }}
        run: echo coveralls here


